CREATE TABLE TBL_EQUIPOS (
ID_EQUIPO BIGINT PRIMARY KEY auto_increment,
TIPO_EQUIPO VARCHAR (30) NOT NULL,
MARCA_MODELO VARCHAR(30) NOT NULL,
FICHA VARCHAR(10),
INVENTARIO VARCHAR (20),
OFICINA VARCHAR (50),
ESTADO VARCHAR (20),
DISCO_DURO VARCHAR (10),
RAM VARCHAR (10),
OBSERVACIONES VARCHAR (100),
SERVICE_TAG VARCHAR (30),
ESTADO_ACTUAL BOOLEAN DEFAULT 1,
FECHA_INGRESO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE TBL_ROLES (
ID_ROL BIGINT PRIMARY KEY auto_increment,
NOM_ROL VARCHAR (100) NOT NULL,
DES_ROL VARCHAR(100) NOT NULL,
ESTADO BOOLEAN DEFAULT 1
);
INSERT INTO TBL_ROLES (NOM_ROL,DES_ROL) values('ADMINISTRADOR','TIENE TODOS LOS PRIVILEGIOS');

CREATE TABLE TBL_OBJETOS (
ID_OBJETO BIGINT PRIMARY KEY AUTO_INCREMENT, 			
NOM_OBJETO VARCHAR(100) NOT NULL, 						
DES_OBJETO VARCHAR(100) NOT NULL, 							
ESTADO BOOLEAN DEFAULT 1 
);
INSERT INTO TBL_OBJETOS (NOM_OBJETO,DES_OBJETO) values('DASHBOARD','PAGINA PRINCIPAL');

CREATE TABLE TBL_PERMISOS (
ID_PERMISO BIGINT PRIMARY KEY AUTO_INCREMENT, 			
FK_ID_ROL BIGINT NOT NULL, 						
FK_ID_OBJETO BIGINT NOT NULL, 
FOREIGN KEY (FK_ID_ROL) REFERENCES TBL_ROLES (ID_ROL),
FOREIGN KEY (FK_ID_OBJETO) REFERENCES TBL_OBJETOS (ID_OBJETO),							
ESTADO BOOLEAN DEFAULT 1 
);
CREATE TABLE TBL_USUARIOS (
ID_USUARIO BIGINT PRIMARY KEY AUTO_INCREMENT, 			
NOM_USUARIO VARCHAR(50)NOT NULL, 						
CONTRASENA VARCHAR(255) NOT NULL, 
COD_ESTADO INT,	
FK_ID_ROL BIGINT ,
FOREIGN KEY (FK_ID_ROL) REFERENCES TBL_ROLES (ID_ROL),
FEC_ULTIMA_CONEXION DATETIME NOT NULL					
);
INSERT INTO TBL_USUARIOS (NOM_USUARIO,CONTRASENA,COD_ESTADO,FK_ID_ROL,FEC_ULTIMA_CONEXION) 
values('ADMINISTRADOR','Ina2025',1,1,now());

CREATE TABLE TBL_ESTADO(
COD_ESTADO INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPCION VARCHAR(10)
);
INSERT INTO TBL_ESTADO (DESCRIPCION) values('ACTIVO');
INSERT INTO TBL_ESTADO (DESCRIPCION) values('INACTIVO');

----------------------------------------------
ALTER TABLE TBL_USUARIOS ADD FOREIGN KEY (COD_ESTADO) REFERENCES TBL_ESTADO(COD_ESTADO);

--------------------------------------------------------------------------------------------------------------------
/* INSERCION DE LOS REGISTROS DE EQUIPOS DE COMPUTO CONTABILIZADOS EN EL INA */
---------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','4577','4-004998','CENTRAL',
'MAL ESTADO','500 GB','N/T', 'FUENTE DE PODER DEFECTUOSA', ' ');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 760','2181','4-001461','CENTRAL',
'BUEN ESTADO','250 GB','4 GB', 'PARA DESCARGAR', ' ');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 330','341','4-003650','CENTRAL',
'BUEN ESTADO','160 GB','1 GB', 'PARA DESCARGAR', ' ');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 380','N/T_1','4-001142','CENTRAL',
'MAL ESTADO',' ','2 GB', 'PARA DESCARGAR', ' ');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 320','5432','4-003529','CENTRAL',
'BUEN ESTADO','80 GB','2 GB', 'PARA DESCARGAR', ' ');
---------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','N/T_2','4-004884','CENTRAL',
'MAL ESTADO','500 GB','2 GB', 'FUENTE DE PODER DEFECTUOSA', ' ');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','4762','4-000232','CENTRAL',
'BUEN ESTADO','500 GB','2 GB', ' ', ' ');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','4760','4-000238','CENTRAL',
'MAL ESTADO','500 GB','2 GB', 'TARJETA MADRE DEFECTUOSA', ' ');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 380','5514','4-000227','CENTRAL',
'BUENO','250 GB','2 GB', 'PARA DESCARGO MEMORIA RAM NO DETECTADA', ' ');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','6314','4-0001561','CENTRAL',
'BUENO','500 GB','4 GB', 'MEMORIA RAM NO DETECTADA', ' ');
-----------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','6310','4-001564','CENTRAL',
'MAL ESTADO',' ','3 GB', 'DISCO DURO MALO CODIGO ERROR 2000-142', '52F15V1');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/GENERICO','5586','4-004856',' ',
'DESCARGADO',' ',' ', 'MAL ESTADO/INSERVIBLE', 'N/T');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 760','4761','4-004856',' ',
'DESCARGADO',' ',' ', 'MAL ESTADO/INSERVIBLE', 'DMYW0L1');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 380','3095','4-001133','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIBLE', '4ZP4KM1(10865649241)');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','6390','4-0001561','CENTRAL',
'DESCARGADO','','', 'MAL ESTADO/INSERVIBLE', '52DD65V1');
--------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX','6290','','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIBLE', '52D65V1 ');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 3780','893','4-000315','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIBLE', 'FV9ZDP1');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 380','5630','4-000349','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', '10855524889(4ZJ3KM1)');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','5002','4-004412','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', '8PNJMM1');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 330','1735','4-000346','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', '4Z62KMI');
-------------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 380','1552','4-000370','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', '7596612325');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 380','6577','4-000314','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', '3HNRRL17598198629');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','HP/TPC-Q969-24','8518','','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', 'CA-IM1207P');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','SIN MARCA/SIN MODELO','6894','4-006350','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', 'SIN SERIE');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','SIN MARCA/SIN MODELO0','6893','4-006350','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', 'DQSY7AL0026F6B01');
------------------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','ACER/ASPIRE ZC-605','6773','','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', 'DQSY7AL0026F6B01');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/380','6667','4-001124','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', '4ZN3KM1');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','HP/500 BMT','6638','N/T','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', 'MY80450D3P');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','HP PAVILION P6000/500 BMT','6635','4-005133','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', 'MX80441H78');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/755','4811','','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', '93WH1GI');
---------------------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','4590','4-004965','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', '5DPK1R1');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 320','4381','2009-/4416672','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', '2W8Y2D1');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','SIN MARCA/SIN MODELO','3919','4-000102','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', '02A040042807');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','GENERICO','3652','4-000099','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', '02A040042747');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 760','2211','','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', '3NYWOLI(7979669749');
-----------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/380','651','','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', 'C4SLLMI-26411289769');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 380','499','4-003950','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', 'C4FJLM1(26389361449');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 780','497','4-004257','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', '67J6CPI(1351666341)');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 780','409','','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', '67H6CP1');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','HP COMPAQ/D22MT','149','4-002834','',
'DESCARGADO','','', 'MAL ESTADO/INSERVIVLE', 'MXD50805KR');
----------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4768','66Q6ZQ1','OFICINA CENTRAL',
'','500 GB','2 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4657','4-004751','OFICINA CENTRAL',
'','500 GB','2 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4648','6G06ZQ1','OFICINA CENTRAL',
'','1 TB','2 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4722','4-004726','OFICINA CENTRAL',
'','500 GB','2 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4675','4-004761','OFICINA CENTRAL',
'','500 GB','2 GB', '', '');
---------------------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4875','4-005036','OFICINA CENTRAL',
'','500 GB','5 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-3567','4-000108','OFICINA CENTRAL',
'','250 GB','2 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4735','4-000326','OFICINA CENTRAL',
'','500 GB','4 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4717','4-004788','OFICINA CENTRAL',
'','500 GB','2 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4810','4-005213','OFICINA CENTRAL',
'','1 TB','2 GB', '', '');
------------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4828','4-004755','OFICINA CENTRAL',
'','500 GB','2 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4651','4-004774','OFICINA CENTRAL',
'','500 GB','2 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5615','4-005115','OFICINA CENTRAL',
'','500 GB','2 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4667','4-004759','OFICINA CENTRAL',
'','320 GB','4 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4504','4-004978','OFICINA CENTRAL',
'','320 GB','6 GB', '', '');
-------------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4717','4-004788','OFICINA CENTRAL',
'','500 GB','2 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4726','4-004785','OFICINA CENTRAL',
'','500 GB','6 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4823','4-005208','OFICINA CENTRAL',
'','500 GB','2 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4674','8XH3XQ2','OFICINA CENTRAL',
'','320 GB','2 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-6298','4-004798','OFICINA CENTRAL',
'','320 GB','4 GB', '', '');
---------------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5842','4-0002010','OFICINA CENTRAL',
'','500 GB','6 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5794','4-000217','OFICINA CENTRAL',
'','500 GB','6 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5846','4-0002013','OFICINA CENTRAL',
'','500 GB','6 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5854','4-0002019','OFICINA CENTRAL',
'','500 GB','5 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-6339','4-001582','OFICINA CENTRAL',
'','320 GB','6 GB', '', '');
-----------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-6490','4-006002','OFICINA CENTRAL',
'','500 GB','6 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-6112','4-005358','OFICINA CENTRAL',
'','500 GB','4 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5786','4-000209','OFICINA CENTRAL',
'','500 GB','4 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5877','4-005162','OFICINA CENTRAL',
'','500 GB','4 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5915','51T7V1','OFICINA CENTRAL',
'','500 GB','4 GB', '', '');
-----------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-6140','4-000414','OFICINA CENTRAL',
'','500 GB','2 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5782','4-000205','OFICINA CENTRAL',
'','500 GB','2 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-6066','4-000297','OFICINA CENTRAL',
'','500 GB','4 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5790','4-000213','OFICINA CENTRAL',
'','500 GB','5 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5869','4-005258','OFICINA CENTRAL',
'','1 TB','4 GB', '', '');
---------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-6291','4-005303','OFICINA CENTRAL',
'','500 GB','4 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5984','4-005291','OFICINA CENTRAL',
'','500 GB','2 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5988','4-005295','OFICINA CENTRAL',
'','1 TB','4 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5477','4-005005','OFICINA CENTRAL',
'','320 GB','4 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-6737','4-006223','',
'','500 GB','8 GGB', '', '');
-----------------------------------------------------------------------------------------------------------------------
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4577','4-004909','',
'FUENTE DE PODER MALA','500 GB','4 GGB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5927','4-000354','',
'FALTA MEMORIA RAM','','', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 380','N/T_11','4-00142','',
'NO ENCENDIA','250 GB','2 GGB', 'PARA DESCARGAR', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-2181','4-001461','',
'FALTA MEMORIA RAM','','', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4577','4-004998','',
'FALTA MEMORIA RAM','500 GB','', '', '');
----------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-341','4-003650','',
'','160 GB','1 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 320','F-4762','4-000232','',
'BUENO','500 GB','2 GB', 'PARA DESCARGAR', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5432','4-003529','',
'BUENO','120 GB','1 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-4760','4-000238','',
'','','', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-6318','V51Z55V','',
'','','', '', '');
----------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5514','4-000227','',
'','','', 'PARA DESCARGAR', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-6314','4-000561','',
'','','', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-6070','4-000301','',
'','','', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5765','4-004887','',
'','','', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO , MARCA_MODELO,FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM, OBSERVACIONES,SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-5900','4-000338','',
'','','', '', '');
------------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA , INVENTARIO, OFICINA, ESTADO, 
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values('CPU','DELL/OPTIPLEX 790','F-6310','4-001564','',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU','DELL/OPTIPLEX 380','N/T_12','4-001400','',
'','','','PARA DESCARGAR','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'DELL/OPTIPLEX 790', '4713','4-004729','CENTRAL',
'DESCARGADO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, 
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'DELL/OPTIPLEX 790', '5892','4-005170','CENTRAL',
'DESCARGADO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU','HP/SFF 280 G9','', '4-010102','CENTRAL','NUEVO',
'256 GB','16 GB','','');
----------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'HP/SFF 280 G9', '', '4-010104', 'CENTRAL','NUEVO',
'256 GB','16 GB','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, 
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'HP/SFF 280 G9', '', '4-010103','CENTRAL','NUEVO',
'256 GB', '16 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU','HP/SFF 280 G9', '', '4-010097','CENTRAL', 'NUEVO',
'256 GB', '16 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, 
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'HP/SFF 280 G9', '', '4-010096','CENTRAL', 'NUEVO',
'256 GB', '16 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'HP/SFF 280 G9', '', '4-010094', 'CENTRAL', 'NUEVO',
'256 GB','16 GB', '','');
----------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'HP/SFF 280 G9','','4-010098','CENTRAL', 'NUEVO',
'256 GB', '16 GB','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'HP/SFF 280 G9', '', '4-010100','CENTRAL','NUEVO',
'256 GB', '16 GB','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'HP/SFF 280 G9', '','4-010032','CENTRAL', 'NUEVO',
'256 GB', '16 GB','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'HP/SFF 280 G9', '','4-010107','CENTRAL','NUEVO',
'256 GB', '16 GB','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'HP/SFF 280 G9', '', '4-010099','CENTRAL','NUEVO',
'256 GB','16 GB','','');
-------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU','HP/SFF 280 G9', '', '4-010095','CENTRAL','NUEVO',
'256 GB', '16 GB', '', '');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'HP/SFF 280 G9','', '4-010033','CENTRAL','NUEVO',
'256 GB','16 GB', '','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'HP/SFF 280 G9', '', '4-010101','CENTRAL','NUEVO',
'256 GB', '16 GB', '','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'HP/SFF 280 G9','','4-010053','CENTRAL','NUEVO',
'256 GB','16 GB','','');
----------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU','HP/SFF 280 G9','','4-010034','CENTRAL','NUEVO',
'256 GB', '16 GB','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'HP/SFF 280 G9','', '4-010058','CENTRAL','NUEVO',
'256 GB','16 GB','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU', 'HP/SFF 280 G9','', '4-010050','CENTRAL','NUEVO',
'256 GB', '16 GB','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU','HP/SFF 280 G9','','4-010051','CENTRAL','NUEVO',
'256 GB', '16 GB','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU','HP/SFF 280 G9','','4-010052','CENTRAL','NUEVO',
'256 GB', '16 GB','','');
-----------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU','HP/SFF 280 G9','','4-010059','SANTA BARBARA','NUEVO',
'256 GB', '16 GB', '','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU','HP/SFF 280 G9','','4-010055','SANTA BARBARA','NUEVO',
'256 GB','16 GB','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU','HP/SFF 280 G9', '','4-010057','SANTA BARBARA','NUEVO',
'256 GB','16 GB','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM,OBSERVACIONES, SERVICE_TAG) values ('CPU', 'HP/SFF 280 G9','','4-010035','SANTA BARBARA','NUEVO',
'256 GB','16 GB','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('CPU','HP/SFF 280 G9','','4-010054','SANTA BARBARA','NUEVO',
'256 GB','16 GB','','');
---------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM,OBSERVACIONES,SERVICE_TAG) values ('CPU','HP/SFF 280 G9','','4-010056','CENTRAL','NUEVO',
'256 GB','16 GB','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('ESCANER','FUJITSU/FI-6140','5086','4-005188','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','344738');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('ESCANER','CANON/IMAGEFORMULA DR-2020U','6914','','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','SP1305A00275TC');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('ESCANER','EPSON/WORKFORCE DS-6500','6859','4-006381','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','PWTZ-005551');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('ESCANER','FUJITSU/FI-6140','5082','4-000336','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','344827');
----------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO,RAM,OBSERVACIONES, SERVICE_TAG) values ('ESCANER','FUJITSU/FI-6140','5078','','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','353169');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('ESCANER','FUJITSU/FI-6140','5068','4-004732','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','344790');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('ESCANER','FUJITSU/FI-6140','5074','4-004732','','DESCARGADO',
'','','MAL ESTADO/INSERVIVLE','353179');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('FOTOCOPIADORA MULFUNCIONAL','CANON/R-14351','7869','4-001677',
'','DESCARGADO','','','MAL ESTADO/INSERVIBLE','21-RYX00731');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA','HP LASERJET 600','6295','4-005311','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','');
----------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA','HP/LASERJEPP600M601','6415','4-00538','CENTRAL',
'MAL ESTADO','','','TONER CON FUGA DE TINTA','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO,
DISCO_DURO, RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA','HP/LASERJEPP3015','5099','4-004953','CENTRAL',
'BUEN ESTADO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM,OBSERVACIONES,SERVICE_TAG) values ('IMPRESORA','HP/LASERJEPP3015','5101','4-000398','CENTRAL','BUEN ESTADO',
'','','TONER CON FUGA DE TINTA','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM,OBSERVACIONES,SERVICE_TAG) values ('IMPRESORA','HP/LASERJET','861','','CENTRAL','BUEN ESTADO',
'','','MAL ESTADO/INSERVIBLE','CNB1N81352');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA','EPSON/L5590','','4-010026','CENTRAL','NUEVO',
'','','','XBV138894');
---------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA','EPSON/L5591','','4-010027','CENTRAL','NUEVO',
'','','','');
INSERT INTO TBL_EQUIPOS(TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA DE CHORRO DE TINTA','CANON/L 250','709','4-000291','CENTRAL',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','JUKA39581');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA DE CHORRO DE TINTA','HP/DESKJET 5940','467','','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','CNO9N111C8');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA DE MATRIZ DE PUNTO','EPSON/FX-890','6207','4-05496','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','NZBY055150');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values('IMPRESORA DE MATRIZ DE PUNTO','EPSON/FX-890','6208','4-005497','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','NZBY055156');
------------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM,OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA DE MATRIZ DE PUNTO','EPSON/FX-2190','4323','','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','FCTY154353');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA DE MATRIZ DE PUNTO','EPSON/P170B','3922','','','DESCARGADO','',
'','MAL ESTADO/INSERVIBLE','NUGY035860');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA DE MATRIZ DE PUNTO','GENIOM/5000','73','4-000350','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','1MW003607');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA LASER','HP/LASER JET P3015','5100','4-004954','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','VNBCC6Y08G');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA LASER','HP/LASER JET 3600N','6093','4-000318','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','CNBCD590PM');
---------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA LASER','HP/LASER JET 3600N','6368','','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','CNBCD5906F');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA LASER','HP/LASER JET P3015','5094','4-000332','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','VNBCC4X16Q');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA LASER','HP/LASER JET 3600N','5096','','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','VNBCC4X174');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA LASER','HP/LASER JET P3015','4874','4-005031','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','VNBCC6Y083');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA LASER','HP/LASER JET 3600N','6437','4-006008','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','CNBCD5905N');
-------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA LASER','LASERJET 600','6332','4-000345','','DESCARGADO',
'','','MAL ESTADO/INSERVIBLE','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA MATRICIAL','EPSON/FX2190','N/T_12','4-000337','','',
'','','MAL ESTADO/INSERVIBLE','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA MATRIZ DE PUNTO','EPSON/P362U FX-2190','5439','4-000333','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','FCTY157769');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA MATRIZ DE PUNTO','EPSON/P362U FX-2190','5219','','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','FCTY15-7768');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA MULTIFUNCIONAL','EPSON/L3210','8526','4-001719','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','XAGB132077');
--------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA MULTIFUNCIONAL','EPSON/L3250','8458','4-001717','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','XAGZ089029');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA MULTIFUNCIONAL','EPSON/L355','6758','','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','S3YK585665');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA MULTIFUNCIONAL','EPSON/L355','6731','','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','S3YK589836');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA','HP/LASERJET P3015','F-7128','4-006345','',
'EFICIENTE','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA','EPSON/PB33A','F-8738','4-007838','',
'EFICIENTE','','','','');
--------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA','HP/LASERJET 600','F-6359','4-000362','',
'FALTA CARTUCHO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA','KYOCERA/ECOSYS 2040','F-8188','4-000427','',
'FALTA CARTUCHO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA','HP/LASERJET P3015','N/T_13','','',
'FALTA CARTUCHO','','','','VNBCC6G365');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA DE TINTA','CANON/TP2700','N/T_14','','',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA DE TINTA','HP/HEWLET PACKARD','F-5100','4-001604','',
'','','','','');
---------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA DE TINTA','SHARCH/AL-204055','F-6031','4-004121','',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA DE TINTA','CANON/IMAGERUNNER1023L','F-4312','4-000261','',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA LASER','HP/LASERJET 2600N','N/T_15','4-003557','',
'','','','','');

-------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('IMPRESORA DE TINTA','CANON/MX472','F-6708','4-0061669','',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL','3135','4-000358','CENTRAL',
'MAL ESTADO','','','PANTALLA DEFECTUOSA','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/E1912H','5795','4-000218','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','CN-OX6MOJ-287223V2FML');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/E1912H','5791','4-000214','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','CN-OX6MOJ-287223V2G5L');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/E1912H','5787','4-000210','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','CN-OX6MOJ-287223V2DAL');
--------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/E1912H','5779','4-000202','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','CN-OX6MOJ-287223V2ORL');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/E1912H','5775','4-000198','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','CN-OXCMOJ-7287223V22ML');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/E1709WC','3117','4-000159','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','CN-OX706H787204H0TOL');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/ST2210B','3096','4-000187','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','CN-OX706H728720410E6L');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/W17E','6917','4-004584/4-006422','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','CNC821PV1D');
--------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/E1709W','3800','4-000279','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','CN-OX706H-72872-04A-28CL');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/HPS1933','6640','4-005138','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','TS20314666');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/HPS1933','6521','4-005132','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','CN-134PMHR');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/E1912H','5968','','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','CN-OX6MOJ7287223V22NL');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/E2011HT','4784','','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','CN-019K59641800BUOEDL');
----------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/SK-8115','523','','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','CNOX706H-72872-04A-1EFL');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','BENQ/','6880','4-006344','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','BENQ/','3574','4-000109','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','BENQ/','6886','4-006345','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','BENQ/','F-6889','4-006343','CENTRAL',
'','','','','');
-----------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','BENQ/','F-7214','4-006590','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','CYBERTECH/','N/T_6','4-003729','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-3172','4-000113','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-1549','4-000371','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-5616','4-005114','CENTRAL',
'','','','','');
-------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-4723','4-004727','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-502','4-003948','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-5631','4-000160','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-5606','4-00514','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-5783','4-00206','CENTRAL',
'','','','','');
-------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-0293','4-003533','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-1764','4-003548','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-4825','4-005209','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-4635','4-005454','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-6340','4-001565','CENTRAL',
'','','','','');
------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-3241','4-000272','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-4101','4-000292','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-4522','4-000293','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-1951','4-001125','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-471','4-004407','CENTRAL',
'','','','','');
--------------------------------------------------------------------------------------------------------------------
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-4794','4-000356','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-6410','4-006003','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-5376','4-000303','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-5855','4-0002021','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-3152','4-000156','CENTRAL',
'','','','','');
--------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-645','4-003952','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-4563','4-005042','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-1513','4-000385','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-4574','4-005224','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-4762','4-004792','CENTRAL',
'','','','','');
------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-7892','4-007260','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-7803','4-006845','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-5380','4-004918','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-5266','4-004888','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-5805','4-005183','CENTRAL',
'','','','','');
--------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-6297','4-004799','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-6302','4-0001562','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-4813','4-003697','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-7515','4-006920','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-0543','4-000224','CENTRAL',
'','','','','');
-------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-0495','4-004256','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-5986','4-005293','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-5275','4-004881','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/','F-6637','4-005143','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','SAMSUNG/','F-3190','4-000172','CENTRAL',
'','','','','');
-----------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','LG 22 PULGS','5236','4-004839','CENTRAL',
'DESCARGA','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL E178WFBC','5250','4-004826','CENTRAL',
'DESCARGADO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010088','CENTRAL',
'NUEVO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010093','CENTRAL',
'NUEVO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010091','CENTRAL',
'NUEVO','','','','');
-------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010047','CENTRAL',
'DESCARGA','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010043','CENTRAL',
'DESCARGADO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010085','CENTRAL',
'NUEVO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010090','CENTRAL',
'NUEVO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010030','CENTRAL',
'NUEVO','','','','');
-----------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010048','CENTRAL',
'DESCARGA','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010083','CENTRAL',
'DESCARGADO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010045','CENTRAL',
'NUEVO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010087','CENTRAL',
'NUEVO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010084','CENTRAL',
'NUEVO','','','','');
----------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010042','CENTRAL',
'DESCARGA','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010049','CENTRAL',
'DESCARGADO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010082','CENTRAL',
'NUEVO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010040','CENTRAL',
'NUEVO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','HP/P22VG5','','4-010089','CENTRAL',
'NUEVO','','','','');
-----------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','SAMSUNG 7535','336','4-000350','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/','F-3497','4-003539','CENTRAL',
'','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL E2011HT','4714','4-004730','CENTRAL',
'DESCARGADO','','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('MONITOR','DELL/E1709WC','408','','',
'DESCARGADO','','','MAL ESTADO/INSERVIBLE','CN-ON300H-64180-12D-04ZL');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('PACK TECLADO Y MOUSE','','10444','4-009983','CENTRAL',
'NUEVO','','','','');
------------------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('PACK TECLADO Y MOUSE','','10748','4-009987','CENTRAL','NUEVO',
'','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values('PACK TECLADO Y MOUSE','','10749','4-009988','CENTRAL','NUEVO',
'','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('PACK TECLADO Y MOUSE','','10745','4-009984','CENTRAL','NUEVO',
'','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('PACK TECLADO Y MOUSE','','10442','4-007981','CENTRAL','NUEVO',
'','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('PACK TECLADO Y MOUSE', '','10747','4-009986','CENTRAL','NUEVO',
'','','','');
---------------------------------------------------------------------------------------------------------
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('PACK TECLADO Y MOUSE', '','10752','4-009991','CENTRAL','NUEVO',
'','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('PACK TECLADO Y MOUSE','','10746','4-009985','CENTRAL','NUEVO',
'','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('PACK TECLADO Y MOUSE','','10443','4-009982','CENTRAL','NUEVO',
'','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('PACK TECLADO Y MOUSE','','10753','4-009982','CENTRAL','NUEVO',
'','','','');
INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
RAM, OBSERVACIONES, SERVICE_TAG) values ('PACK TECLADO Y MOUSE','','10739','4-009978','CENTRAL','NUEVO',
'','','','');
-----------------------------------------------------------------------------------------------------------
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values ('PACK TECLADO Y MOUSE', '','10750','4-009989','CENTRAL','NUEVO',
 '','','','');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values ('PACK TECLADO Y MOUSE','','10740','4-009979','CENTRAL','NUEVO',
 '','','','');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values ('PACK TECLADO Y MOUSE','','10751','4-009990','CENTRAL','NUEVO',
 '','','','');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values ('PACK TECLADO Y MOUSE', '','10741','4-007980','CENTRAL','NUEVO',
 '','','','');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values ('TECLADO', 'HP-PR11001U','8605','4-007612','CENTRAL','DESCARGADO',
 '','','MAL ESTADO/INSERVIBLE','');
 --------------------------------------------------------------------------------------------------------
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values('TECLADO', 'DELL/SK-8115','407','','','DESCARGADO','','',
 'MAL ESTADO/INSERVIBLE','CN-ODJ145-71616-0CH-06RQ');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values('TECLADO','DELL/SK-8115','6075','','','DESCARGADO','','',
 'MAL ESTADO/INSERVIBLE','CN-ODJ415-71616-082-OCTV');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values('TECLADO','DELL/SK-8115','403','','','DESCARGADO','','',
 'MAL ESTADO/ INSERVIBLE','CN-0DJ415-71616-0AM-5QM');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values ('TECLADO','HP/SK-1688','147','4-002836','','DESCARGADO',
 '','','MAL ESTADO/INSERVIBLE','C0412065188');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values ('TECLADO','DELL/NMB003','6587','4-000240','','DESCARGADO',
 '','','MAL ESTADO/INSERVIBLE','CN00J415-71616-034-03TI');
 -----------------------------------------------------------------------------------------------------------------
  INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values('TECLADO', 'DELL/KB212-B','6802','4-006289','','DESCARGADO','','',
 'MAL ESTADO/INSERVIBLE','CN-OC639N71616-56H-16H-A00');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values('TECLADO','ACER/OM-130006A/K','6768','','','DESCARGADO','','',
 'MAL ESTADO/INSERVIBLE','44603666KY00');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values('TECLADO','DELL/SK-8115','5610','4-003573','','DESCARGADO','','',
 'MAL ESTADO/ INSERVIBLE','CN-ODJ41571616950270');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values ('TECLADO','HP/KB-0316','5528','4-000769','','DESCARGADO',
 '','','MAL ESTADO/INSERVIBLE','BC337OBVUQOWP');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values ('TECLADO','DELL/KB-228','N/T_4','','','DESCARGADO',
 '','','MAL ESTADO/INSERVIBLE','CN-OKHCC7161615ROBFCADO');
 ---------------------------------------------------------------------------------------------------------------
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values('TECLADO', 'GENERICO','5410','4-004445','','DESCARGADO','','',
 'MAL ESTADO/INSERVIBLE','N/T');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values('TECLADO','ELITE','5381','4-004920','','DESCARGADO','','',
 'MAL ESTADO/INSERVIBLE','N/T');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values('TECLADO','DELL/SK-8115','5004','4-004414','','DESCARGADO','','',
 'MAL ESTADO/ INSERVIBLE','CN-ODJ415-716116-OCH-03C9');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values ('TECLADO','DELL/KB-0228','4871','','','DESCARGADO',
 '','','MAL ESTADO/INSERVIBLE','CN-OKHCC7-71616-15R-OBHGADO');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values ('TECLADO','DELL/KB-0228-B','4669','4-004767','','DESCARGADO',
 '','','MAL ESTADO/INSERVIBLE','CN-OJ6WFJ-73571-11K-03M4-AOO');
 ---------------------------------------------------------------------------------------------------------------
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values('TECLADO', 'DELL','3918','','','DESCARGADO','','',
 'MAL ESTADO/INSERVIBLE','01A040113678');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values('TECLADO','DELL/SK-8116','522','','','DESCARGADO','','',
 'MAL ESTADO/INSERVIBLE','CN-ODJ415-71616-03R-06CB');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values('TECLADO','ACER/','6774','4-006199','OFICINA CENTRAL','','','',
 '','');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values('TECLADO','DELL/','F-383','4-003580','OFICINA CENTRAL','','','',
 '','');
 INSERT INTO TBL_EQUIPOS (TIPO_EQUIPO, MARCA_MODELO, FICHA, INVENTARIO, OFICINA, ESTADO, DISCO_DURO,
 RAM, OBSERVACIONES, SERVICE_TAG) values('TECLADO','DELL/','F-4865','4-005429','OFICINA CENTRAL','','','',
 '','');